{
 "title": "Nginx Ingress Controller",
 "description": "Show stats from the kubernetes nginx ingress",
 "tags": [
  "prometheus",
  "nginx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_bytes_total, instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nginx_requests_total{server_zone!=\"*\", server_zone!=\"_\", instance=~\"^$instance$\"}, server_zone)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_upstream_bytes_total{instance=~\"^$instance$\"}, upstream)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_connections_total{instance=~\"^$instance$\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total{instance=~\"^$instance$\", server_zone=~\"^$host$\"}[5m])) by (status_code)",
     "legendFormat": "{{ status_code }} "
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_bytes_total{instance=~\"^$instance$\", server_zone=~\"^$host$\", server_zone!=\"*\", server_zone!=\"_\"}[1m])) by (server_zone)",
     "legendFormat": "{{server_zone}}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_upstream_responses_total{instance=~\"^$instance$\", upstream =~\"^$upstream$\"}[1m])) by (upstream)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_upstream_response_msecs_avg{instance=~\"^$instance$\",upstream=~\"^$upstream$\"}",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Worldmap",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(nginx_filterzone_responses_total) by (key)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{key}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}