{
 "title": "Synology NAS",
 "description": "Basic details about my Synology NAS DS918+",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Quick Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synology DiskStation Model",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "918" }
   ]
  },
  {
   "title": "Total Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_frequency_max_hertz{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\",fstype=\"btrfs\",mountpoint=\"/rootfs/volume1\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    { "expr": "4" }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\",mountpoint=\"/rootfs/volume1\"} - node_filesystem_avail_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\",fstype=\"btrfs\",mountpoint=\"/rootfs/volume1\"}",
     "legendFormat": "Used - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Current Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  { "title": "Basic Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"} - node_memory_MemFree_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"} - node_memory_Buffers_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"} - node_memory_Cached_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "0-sum(irate(node_network_transmit_bytes_total{kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"synology-nas\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}